In [4]:
import pandas as pd

path = './'
file_name = 'binf6111qc_patient.xlsx'

In [5]:
patient_details = pd.read_excel(path + file_name, sheet_name = 0)
sample_details = pd.read_excel(path + file_name, sheet_name = 1)
sample_purity = pd.read_excel(path+file_name, sheet_name = 2)
patient_details.insert(0, 'id', range(1, 1 + len(patient_details)))
sample_details.insert(0, 'id', range(1, 1 + len(sample_details)))
sample_purity.insert(0, 'id', range(1, 1 + len(sample_purity)))

In [6]:
patient_details.head()

,id,patient_id,sex,age_at_diagnosis,age_at_death,vital_status,hospital,enrolment_date
0,1,P000201,Male,7.0,NaN,Alive,NSW Hospital1,2017-09-01
1,2,P000601,Female,14.0,NaN,Alive,NSW Hospital1,2017-10-01
2,3,P000803,Male,14.0,17.0,Dead,NSW Hospital2,2019-06-01
3,4,P000806,Female,8.0,13.0,Dead,QLD Hospital1,2017-11-01
4,5,P000808,Female,14.0,NaN,Alive,SA Hospital1,2019-04-01

In [7]:
sample_details.head()

,id,sample_id,patient_id,manifest_id,matched_normal_id,study,age_at_sample,cancer_category,cancer_type,diagnosis,...,ploidy,msi_status,amber_qc,amber_tumor_baf,contamination,rna_uniq_mapped_reads,rna_uniq_mapped_reads_pct,rna_rin,mut_burden_mb,wgs_date (d/m/y)
0,1,LKCGP-P000201-244412-01-06-01-R1,P000201,R_160805_EMIMOU_LIONSDNA_M017,LKCGP-P000201-244413-01-06-07-G1,PRISM,10,Solid tumour,Other,Solid other,...,3.9910,MSS,PASS,0.4984,0.000,89622940.0,78.06,6.2,2.353190,2017-10-03
1,2,LKCGP-P000601-245664-01-06-01-D1,P000601,R_160805_EMIMOU_LIONSDNA_M021,LKCGP-P000601-245666-02-06-07-G1,PRISM,14,Solid tumour,Other,Solid other,...,4.2017,MSS,PASS,0.4980,0.000,75481573.0,64.77,4.6,0.524322,2017-11-02
2,3,LKCGP-P000803-283756-01-02-03-R2,P000803,R_160805_EMIMOU_LIONSDNA_M084_pt2,LKCGP-P000803-262693-01-02-09-G2,PRISM,17,HM,Leukaemia,BALL,...,2.0153,MSS,FAIL,0.5145,0.000,NaN,NaN,NaN,24.748841,2019-07-03
3,4,LKCGP-P000806-246360-01-04-01-D1,P000806,R_160805_EMIMOU_LIONSDNA_M023,LKCGP-P000806-246359-02-04-07-G1,PRISM,12,Solid tumour,Sarcoma,EWS,...,2.5825,MSS,WARN,0.4981,0.005,74581540.0,70.56,5.6,1.144154,2017-11-23
4,5,LKCGP-P000808-277070-01-02-03-R2,P000808,R_160805_EMIMOU_LIONSDNA_M075_pt1,LKCGP-P000808-277069-01-02-01-G2,PRISM,18,HM,Leukaemia,AML,...,2.0068,MSS,FAIL,0.4975,0.197,90299653.0,80.22,7.4,2.576817,2019-05-01

In [8]:
sample_purity.head()

,id,sampleId,gender,status,qcStatus,purity,normFactor,score,somaticPenalty,ploidy,...,minPloidy,maxPloidy,minDiploidProportion,maxDiploidProportion,msIndelsPerMb,msStatus,tmbPerMb,tmbStatus,tml,tmlStatus
0,1,LKCGP-P000201-244412-01-06-01-R1,MALE,NORMAL,FAIL_SEGMENT,0.14,0.88,0.3684,0.0023,3.9910,...,3.9472,4.1094,0.0126,0.0243,0.0717,MSS,2.4991,LOW,65,LOW
1,2,LKCGP-P000601-245664-01-06-01-D1,FEMALE,NORMAL,FAIL_SEGMENT,0.18,0.84,0.4224,0.0150,4.2017,...,3.4258,5.0316,0.0049,0.0167,0.0532,MSS,0.5568,LOW,5,LOW
2,3,LKCGP-P000803-283756-01-02-03-R2,MALE_KLINEFELTER,NORMAL,FAIL_SEGMENT,0.96,0.99,0.4393,0.0075,2.0153,...,2.0149,2.0353,0.7916,0.7930,0.2963,MSS,1.9091,LOW,20,LOW
3,4,LKCGP-P000806-246360-01-04-01-D1,FEMALE,NORMAL,FAIL_SEGMENT,0.14,0.94,0.3254,0.0138,2.5825,...,2.4531,3.0394,0.1990,0.3298,0.0672,MSS,1.2148,LOW,24,LOW
4,5,LKCGP-P000808-277070-01-02-03-R2,FEMALE,SOMATIC,FAIL_GENDER,0.60,1.00,0.2653,0.0000,2.0068,...,2.0041,2.0074,0.9694,0.9851,0.0507,MSS,2.7359,LOW,72,LOW

In [20]:
from itertools import chain
col_list = [x for x in chain(range(13), range(23, 24))]
sample = sample_details.iloc[:, col_list].copy()
sample.rename(columns = {'wgs_date (d/m/y)':'wgs_date'}, inplace = True)
sample.head()

,id,sample_id,patient_id,manifest_id,matched_normal_id,study,age_at_sample,cancer_category,cancer_type,diagnosis,final_diagnosis,event_type,tissue,wgs_date
0,1,LKCGP-P000201-244412-01-06-01-R1,P000201,R_160805_EMIMOU_LIONSDNA_M017,LKCGP-P000201-244413-01-06-07-G1,PRISM,10,Solid tumour,Other,Solid other,"Other, carcinoma, hepatocellular",R1,TT,2017-10-03
1,2,LKCGP-P000601-245664-01-06-01-D1,P000601,R_160805_EMIMOU_LIONSDNA_M021,LKCGP-P000601-245666-02-06-07-G1,PRISM,14,Solid tumour,Other,Solid other,"Other, carcinoma, adenocarcinoma lung",D1,TT,2017-11-02
2,3,LKCGP-P000803-283756-01-02-03-R2,P000803,R_160805_EMIMOU_LIONSDNA_M084_pt2,LKCGP-P000803-262693-01-02-09-G2,PRISM,17,HM,Leukaemia,BALL,"ALL, B precursor",R2,BMA,2019-07-03
3,4,LKCGP-P000806-246360-01-04-01-D1,P000806,R_160805_EMIMOU_LIONSDNA_M023,LKCGP-P000806-246359-02-04-07-G1,PRISM,12,Solid tumour,Sarcoma,EWS,Ewing's sarcoma,R2,TT,2017-11-23
4,5,LKCGP-P000808-277070-01-02-03-R2,P000808,R_160805_EMIMOU_LIONSDNA_M075_pt1,LKCGP-P000808-277069-01-02-01-G2,PRISM,18,HM,Leukaemia,AML,AML,R2,BMA,2019-05-01

In [38]:
sample_purity_metrics = pd.concat(
    [sample_purity.iloc[:, range(5)].copy(), 
     sample_details.iloc[:, range(16, 23)].copy(),
     sample_purity.iloc[:, range(5, 25)].copy()], 
    axis = 1)
sample_purity_metrics.columns = ['id', 'sample_id', 'gender_from_sample', 'status', 'qc_status', 
                                 'amber_qc', 'amber_tumor_baf', 'contamination', 'rna_uniq_mapped_reads', 'rna_uniq_mapped_reads_pct', 
                                 'rna_rin', 'mut_burden_mb', 'purity', 'norm_factor', 'score', 'somatic_penalty', 'ploidy', 
                                 'diploid_proportion', 'polyclonal_proportion', 'whole_genome_duplication', 'min_purity', 'max_purity', 
                                 'min_ploidy', 'max_ploidy', 'min_diploid_proportion', 'max_diploid_proportion', 
                                 'ms_indels_per_mb', 'ms_status', 'tmb_per_mb', 'tmb_status', 'tml', 'tml_status']
sample_purity_metrics.columns

Index(['id', 'sample_id', 'gender_from_sample', 'status', 'qc_status',
       'amber_qc', 'amber_tumor_baf', 'contamination', 'rna_uniq_mapped_reads',
       'rna_uniq_mapped_reads_pct', 'rna_rin', 'mut_burden_mb', 'purity',
       'norm_factor', 'score', 'somatic_penalty', 'ploidy',
       'diploid_proportion', 'polyclonal_proportion',
       'whole_genome_duplication', 'min_purity', 'max_purity', 'min_ploidy',
       'max_ploidy', 'min_diploid_proportion', 'max_diploid_proportion',
       'ms_indels_per_mb', 'ms_status', 'tmb_per_mb', 'tmb_status', 'tml',
       'tml_status'],
      dtype='object')

In [17]:
from config import db_creds

In [39]:
from sqlalchemy import create_engine
from sqlalchemy.engine.url import URL

connect_args={'ssl':{'fake_flag_to_enable_tls': True}}
engine = create_engine("mysql+pymysql://{user}:{pw}@{host}:{port}/{db}"
                       .format(user=db_creds['user'],
                               pw=db_creds['password'],
                               host=db_creds['host'],
                               port=db_creds['port'],
                               db=db_creds['database']),
                       connect_args=connect_args
                      )

# patient_details.to_sql('patient', con = engine, if_exists = 'append', index = False)
# sample.to_sql('sample', con = engine, if_exists = 'append', index = False)
sample_purity_metrics.to_sql('sample_purity_metrics', con = engine, if_exists = 'append', index = False)

In [6]:
import pymysql

connection = pymysql.connect(
    host=db_creds['host'],
    user=db_creds['user'],
    passwd=db_creds['password'],
    db=db_creds['database'],
    port = db_creds['port'],
    ssl={'ssl':{'ca': '~/.qc-server-keys/ca.pem'}}
)
cursor = connection.cursor()

In [8]:
sql = "SELECT * FROM `patient`"
cursor.execute(sql)
result = cursor.fetchall()
for i in result:
    print(i)
connection.close()

(1, 'P000201', 'Male', 7, None, 'Alive', 'NSW Hospital1', datetime.date(2017, 9, 1))
(2, 'P000601', 'Female', 14, None, 'Alive', 'NSW Hospital1', datetime.date(2017, 10, 1))
(3, 'P000803', 'Male', 14, 17, 'Dead', 'NSW Hospital2', datetime.date(2019, 6, 1))
(4, 'P000806', 'Female', 8, 13, 'Dead', 'QLD Hospital1', datetime.date(2017, 11, 1))
(5, 'P000808', 'Female', 14, None, 'Alive', 'SA Hospital1', datetime.date(2019, 4, 1))
(6, 'P001103', 'Female', 0, None, 'Alive', 'NSW Hospital2', datetime.date(2018, 12, 1))
(7, 'P001502', 'Male', 22, 24, 'Dead', 'NSW Hospital3', datetime.date(2018, 6, 1))
(8, 'P001805', 'Male', 8, None, 'Alive', 'VIC Hospital1', datetime.date(2019, 6, 1))
(9, 'P001905', 'Male', 14, 15, 'Dead', 'VIC Hospital1', datetime.date(2019, 6, 1))
(10, 'P002006', 'Male', 12, None, 'Alive', 'QLD Hospital1', datetime.date(2018, 6, 1))
(11, 'P002102', 'Female', 14, 15, 'Dead', 'NSW Hospital3', datetime.date(2018, 7, 1))
(12, 'P002207', 'Female', 4, None, 'Alive', 'WA Hospital1', datetime.date(2019, 6, 1))
(13, 'P002301', 'Male', 13, 13, 'Dead', 'NSW Hospital1', datetime.date(2018, 5, 1))
(14, 'P002307', 'Female', 1, 1, 'Dead', 'WA Hospital1', datetime.date(2019, 7, 1))
(15, 'P002601', 'Female', 17, 18, 'Dead', 'NSW Hospital1', datetime.date(2018, 6, 1))
(16, 'P002704', 'Female', 14, None, 'Alive', 'VIC Hospital2', datetime.date(2019, 2, 1))
(17, 'P002805', 'Male', None, None, 'Alive', 'VIC Hospital1', datetime.date(2019, 12, 1))
(18, 'P002902', 'Male', 9, None, 'Alive', 'NSW Hospital3', datetime.date(2019, 1, 1))
(19, 'P003001', 'Male', 6, 9, 'Dead', 'NSW Hospital1', datetime.date(2018, 7, 1))
(20, 'P003307', 'Male', 16, None, 'Alive', 'WA Hospital1', datetime.date(2019, 12, 1))
(21, 'P003506', 'Female', 0, None, 'Alive', 'QLD Hospital1', datetime.date(2019, 2, 1))
(22, 'P003607', 'Female', 12, None, 'Alive', 'WA Hospital1', datetime.date(2020, 1, 1))
(23, 'P003804', 'Male', 17, None, 'Alive', 'VIC Hospital2', datetime.date(2019, 4, 1))
(24, 'P004301', 'Male', 11, 13, 'Dead', 'NSW Hospital1', datetime.date(2018, 12, 1))
(25, 'P004801', 'Male', 10, None, 'Alive', 'NSW Hospital1', datetime.date(2019, 2, 1))
(26, 'P005001', 'Female', 1, None, 'Alive', 'NSW Hospital1', datetime.date(2019, 3, 1))
(27, 'P005202', 'Male', 6, None, 'Alive', 'NSW Hospital3', datetime.date(2019, 9, 1))
(28, 'P005304', 'Female', 4, None, 'Alive', 'VIC Hospital2', datetime.date(2019, 10, 1))
(29, 'P005404', 'Female', 0, None, 'Alive', 'VIC Hospital2', datetime.date(2019, 10, 1))
(30, 'P005501', 'Male', 14, 15, 'Dead', 'NSW Hospital1', datetime.date(2019, 4, 1))
(31, 'P005602', 'Female', None, 15, 'Dead', 'NSW Hospital3', datetime.date(2019, 10, 1))
(32, 'P005702', 'Male', 10, None, 'Alive', 'NSW Hospital3', datetime.date(2019, 10, 1))
(33, 'P005704', 'Female', 3, None, 'Alive', 'VIC Hospital2', datetime.date(2019, 11, 1))
(34, 'P005801', 'Female', 6, 6, 'Dead', 'NSW Hospital1', datetime.date(2019, 6, 1))
(35, 'P005906', 'Male', 8, None, 'Alive', 'QLD Hospital1', datetime.date(2020, 4, 1))
(36, 'P006204', 'Female', 4, None, 'Alive', 'VIC Hospital2', datetime.date(2020, 2, 1))
(37, 'P006301', 'Male', 8, 9, 'Dead', 'NSW Hospital1', datetime.date(2019, 8, 1))
(38, 'P006304', 'Female', 11, None, 'Alive', 'VIC Hospital2', datetime.date(2020, 2, 1))
(39, 'P006404', 'Male', 10, None, 'Alive', 'VIC Hospital2', datetime.date(2020, 3, 1))
(40, 'P006501', 'Male', 13, 14, 'Dead', 'NSW Hospital1', datetime.date(2019, 8, 1))
(41, 'P006502', 'Male', 1, None, 'Alive', 'NSW Hospital3', datetime.date(2020, 1, 1))
(42, 'P006904', 'Female', 16, None, 'Alive', 'VIC Hospital2', datetime.date(2020, 4, 1))
(43, 'P007104', 'Female', 16, None, 'Alive', 'VIC Hospital2', datetime.date(2020, 4, 1))
(44, 'T000101', 'Male', 3, 4, 'Dead', 'NSW Hospital1', datetime.date(2015, 6, 1))
(45, 'T000601', 'Female', 10, 18, 'Dead', 'NSW Hospital1', datetime.date(2015, 9, 1))
(46, 'T000801', 'Male', 6, 9, 'Dead', 'NSW Hospital1', datetime.date(2015, 9, 1))
(47, 'T000901', 'Male', 7, None, 'Alive', 'NSW Hospital1', datetime.date(2015, 9, 1))
(48, 'T001101', 'Male', 1, 2, 'Dead', 'NSW Hospital1', datetime.date(2015, 10, 1))